#!/usr/bin/env python

# ADC Pins
ADC_BATTERY_STATUS_PIN_1 = 0
ADC_BATTERY_STATUS_PIN_2 = 1
ADC_BATTERY_LEVEL_PIN = 2
ADC_WATER_TEMP_PIN = 3
ADC_EC_PIN = 4
ADC_WATER_LEVEL_PIN = 5

# GPIO Pins
GPIO_EXT_INTERRUPT_PIN = 2
GPIO_PUMP_PIN = 3
GPIO_CENTER_BUTTON_PIN = 4
GPIO_EC_PIN = 5
GPIO_PLANT_FAN = 6
GPIO_RED_LIGHTS_PIN = 7
GPIO_WATER_LEVEL = 8
GPIO_LIGHTS_BRIGHTNESS_PIN = 9
GPIO_EPS_FAN = 10
GPIO_HALL_EFFECT_PIN = 11
GPIO_RIGHT_BUTTON_PIN = 12
GPIO_LEFT_BUTTON_PIN = 13
GPIO_DOOR_MOTOR_OPEN = 14
GPIO_DOOR_MOTOR_CLOSE = 15
GPIO_ROTATION_LEFT = 16
GPIO_ROTATION_RIGHT = 17
GPIO_TEMP_HUMIDITY_PIN_1 = 20
GPIO_TEMP_HUMIDITY_PIN_2 = 21
